bio/urls.py
# patcurryworks.com/bio/urls.py
from django.urls import path
from bio import views

app_name = 'bio'


urlpatterns = [
    path('', views.index, name='index'),
    path('resume', views.resume, name='resume'),
]

workouts/urls.py
from django.urls import path, re_path
from django.views.generic import TemplateView
from workouts import views
from workouts import api_views

app_name='workouts'

urlpatterns = [

    ############################
    # normal django view urls
    ############################
    # workouts index view
    path('', TemplateView.as_view(template_name='workouts/workout_index.html'), name='WorkoutIndex'),

    # sessions
    path('sessions/', views.SessionList.as_view(), name='SessionList'),
    path('sessions/new/', views.SessionCreate.as_view(), name='SessionCreate'),
    re_path(r'^sessions/(?P<pk>[0-9]+)/$', views.SessionDetail.as_view(), name='SessionDetail'),
    re_path(r'^sessions/(?P<pk>[0-9]+)/update/$', views.SessionUpdate.as_view(), name='SessionUpdate'),
    re_path(r'^sessions/(?P<pk>[0-9]+)/delete/$', views.SessionDelete.as_view(), name='SessionDelete'),

    # sessions - sets
    re_path(r'^sessions/(?P<pk>[0-9]+)/sets/$', views.SetListBySession.as_view(), name='SetListBySession'),
    re_path(r'^sessions/(?P<pk>[0-9]+)/sets/new$', views.SetCreate.as_view(), name='SetCreate'),


    # exercises
    path('exercises/', views.ExerciseList.as_view(), name='ExerciseList'),
    path('exercises/new/', views.ExerciseCreate.as_view(), name='ExerciseCreate'),
    re_path(r'^exercises/(?P<slug>[-\w]*)/$', views.ExerciseDetail.as_view(), name='ExerciseDetail'),
    re_path(r'^exercises/(?P<slug>[-\w]*)/update/$', views.ExerciseUpdate.as_view(), name='ExerciseUpdate'),
    re_path(r'^exercises/(?P<slug>[-\w]*)/delete/$', views.ExerciseDelete.as_view(), name='ExerciseDelete'),

    # exercises - sets
    re_path(r'^exercises/(?P<slug>[-\w]*)/sets/$', views.SetListByExercise.as_view(), name='SetListByExercise'),



    ############################
    # django rest framework urls
    ############################

    # sessions
    path('api/sessions/', api_views.SessionList.as_view(), name='SessionListAPI'),
    re_path(r'^api/sessions/(?P<pk>[0-9]+)/$', api_views.SessionDetail.as_view(), name='SessionDetailAPI'),

    #sets
    path('api/sets/', api_views.SetList.as_view(), name='SetListAPI'),
    re_path(r'^api/sets/(?P<pk>[0-9]+)/$', api_views.SetDetail.as_view(), name='SetDetailAPI'),

    # exercises
    path('api/exercises/', api_views.ExerciseList.as_view(), name='ExerciseListAPI'),
    re_path(r'^api/exercises/(?P<pk>[0-9]+)/$', api_views.ExerciseDetail.as_view(), name='ExerciseDetailAPI'),

    ############################
    # graphql urls ?
    ############################

]

workouts/models.py
# patcurryworks.com/workouts/models.py
from django.db import models
from django.utils.text import slugify
import datetime

"""
There needs to be a many to many relationship between exercise and set.


https://www.medicinenet.com/weight_lifting/article.htm#how_do_i_go_about_lifting_for_tone_and_endurance
Sets and reps are the terms used to describe the number of times you perform an exercise. A rep is the number of times you perform a specific exercise, and a set is the number of cycles of reps that you complete. For example, suppose you complete 15 reps of a bench press. You would say you've completed "one set of 15 reps." A set can be any number of reps, so if you complete 10 reps of a bench press, you would say you've completed "one set of 10 reps," and if you complete just five reps, then that would be "one set of five reps."
"""


SECONDS = 'sec'
REPETITIONS = 'reps'
UNIT_CHOICES = (
    (SECONDS, 'seconds'),
    (REPETITIONS, 'repetitions'),
)


class Exercise(models.Model):
    """This is the smallest individual unit. Each exercise should be unique"""
    title = models.CharField(max_length=50, unique=True)
    exercise_slug = models.SlugField(max_length=50, unique=True)

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        self.exercise_slug = slugify(self.title)
        super(Exercise, self).save(*args, **kwargs)


class Session(models.Model):
    """This session can have many sets of different types."""
    pub_date= models.DateField(auto_now_add=True)
    title = models.CharField(max_length=100, blank=True)
    session_slug = models.SlugField(max_length=100, blank=True, null=True)
    exercises = models.ManyToManyField(
        Exercise,
        through='Set',
        through_fields=('session', 'exercise'),
        #related_name='sessions',
    )

    def save(self, *args, **kwargs):
        d = datetime.datetime.today().strftime('%Y-%m-%d')
        self.session_slug = slugify(self.title + '-' + d)
        super(Session, self).save(*args, **kwargs)

class Set(models.Model):
    """This set can have many repetitions of one exercise.
    Sit is going to be a through field for the relationship between
    the Exercise and Session models."""
    session = models.ForeignKey(Session, on_delete=models.CASCADE, blank=True, null=True)
    exercise = models.ForeignKey(Exercise, on_delete=models.CASCADE, blank=True, null=True)
    amount = models.IntegerField(default=1, blank=True, null=True)
    units = models.CharField(
        max_length=20,
        choices=UNIT_CHOICES,
        default=REPETITIONS
    )

workouts/views.py
# patcurryworks.com/workouts/views.py
from django.shortcuts import get_object_or_404
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, DetailView, TemplateView
from django.views.generic import CreateView, UpdateView, DeleteView
from workouts.models import Exercise, Set, Session


# Session views
class SessionList(ListView):
    model = Session

    
class SessionDetail(DetailView):
    """The sets will be creatable from this page."""
    model = Session

    
class SessionCreate(CreateView):
    model = Session
    fields = ['title']
    template_name = 'workouts/session_create.html'

    def get_success_url(self):
        return reverse('workouts:SessionDetail', kwargs={'pk': self.object.pk})

    
class SessionUpdate(UpdateView):
    model = Session
    fields = ['title']
    success_url = reverse_lazy('workouts:SessionList')

    
class SessionDelete(DeleteView):
    model = Session
    success_url = reverse_lazy('workouts:SessionList')


# Exercise views
class ExerciseList(ListView):
    model = Exercise


class ExerciseDetail(DetailView):
    model = Exercise
    slug_field = 'exercise_slug'


class ExerciseCreate(CreateView):
    model = Exercise
    fields = ['title']
    template_name = 'workouts/exercise_create.html'

    def get_success_url(self):
        return reverse('workouts:ExerciseDetail', kwargs={'slug': self.object.exercise_slug})


class ExerciseUpdate(UpdateView):
    model = Exercise
    fields = ['title']
    slug_field = 'exercise_slug'
    success_url = reverse_lazy('workouts:ExerciseList')

    
class ExerciseDelete(DeleteView):
    model = Exercise
    slug_field = 'exercise_slug'
    success_url = reverse_lazy('workouts:ExerciseList')


# Set views
class SetListBySession(ListView):

    def get_queryset(self):
        self.session = get_object_or_404(Session, pk=self.kwargs['pk'])
        return Set.objects.filter(session=self.session)


class SetListByExercise(ListView):

    def get_queryset(self):
        self.exercise = get_object_or_404(Exercise, exercise_slug=self.kwargs['slug'])
        return Set.objects.filter(exercise=self.exercise)


class SetCreate(CreateView):
    model = Set
    fields = ('exercise', 'amount', 'units')
    template_name = 'workouts/set_create.html'

    def dispatch(self, request, *args, **kwargs):
        """
        Overridden so we can make sure the `Session` instance exists
        before going any further.
        """
        self.session = get_object_or_404(Session, pk=kwargs['pk'])
        return super().dispatch(request, *args, **kwargs)
    
    def form_valid(self, form):
        """
        Overridden to add the Session relation to the `Set` instance.
        """
        form.instance.session = self.session
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('workouts:SessionDetail', kwargs={'pk': self.session.pk})

templates/workouts/exercise_confirm_delete.html
<!-- patcurryworks/templates/workouts/exercise_confirm_delete.html -->
Confirm Delete
<form action="" method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <input type="submit" value="Confirm" />
</form>

templates/workouts/exercise_create.html
<!-- patcurryworks/templates/workouts/exercise_create.html -->
{% extends "base.html" %}
{% load static %}

{% block content %}
<div class="exercises">
  <h1>Exercise Create</h1>
  {% include "workouts/exercise_form.html" %}
  <a href="{% url 'workouts:ExerciseList' %}">Back to Exercise List</a>
</div>
{% endblock content %}

templates/workouts/exercise_detail.html
<!-- patcurryworks.com/templates/workouts/exercise_detail.html -->
{% extends "base.html" %}

{% block content %}
<h2>{{ object.title }}</h2>

<h3>Sets</h3>
{% for set in object.set_set.all %}
<h4>Session: {{ set.session.title }} - {{ set.session.pub_date }}</h4>
<p>Amount: {{ set.amount }} {{ set.units }}</p>
{% endfor %}
{% endblock content %}

templates/workouts/exercise_form.html
<!-- patcurryworks/templates/workouts/exercise_form.html -->
  <div class="exercise-form">
    <form action="" method="post">
      {% csrf_token %}
      {{ form.as_p }}
    </form>
  </div>

templates/workouts/exercise_list.html
<!-- patcurryworks.com/templates/workouts/exercise_list.html -->
{% extends "base.html" %}

{% block content %}
<div class="exercises">
  <h1>Exercise List</h1>
  <div class="exercise-list">
  {% if object_list %}
  {% for exercise in object_list %}
  <h4>{{ exercise.title }}</h4>
  {% endfor %}
  {% else %}
  <p>no exercises yet</p>
  {% endif %}
  </div>
</div>
{% endblock content %}

templates/workouts/session_confirm_delete.html
<!-- patcurryworks/templates/workouts/session_confirm_delete.html -->
Confirm Delete
<form action="" method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <input type="submit" value="Confirm" />
</form>

templates/workouts/session_create.html
<!-- patcurryworks/templates/workouts/session_create.html -->
{% extends "base.html" %}
{% load static %}

{% block content %}
<div class="sessions">
  <h1>Session Create</h1>
  {% include "workouts/session_form.html" %}
</div>
{% endblock content %}

templates/workouts/session_detail.html
<!-- patcurryworks.com/templates/workouts/session_detail.html -->
{% extends "base.html" %}

{% block content %}
<h2>{{ object.title }} - {{ object.pub_date }}</h2>

<h3>Sets</h3>

<!-- this should have a different link class -->
<p><a class="link workouts" href="{% url 'workouts:SessionList' %}">Back to Session List</a></p>
<p><a class="link workouts" href="{% url 'workouts:SetCreate' object.pk %}">Add New Set</a></p>
<p>How do I get a set count? </p>
<hr />

{% if object.set_set.all %}
  Total sets: {{ object.set_set.all|length }}
  <hr />
  <h3>Sets</h3>
  {% for set in object.set_set.all %}
    <p>{{ set.exercise.title }} - {{ set.amount }} {{ set.units }}</p>
  {% endfor %}
{% else %}
    <p> No sets yet</p>
{% endif %}

{% endblock content %}

templates/workouts/session_form.html
<!-- patcurryworks/templates/workouts/session_form.html -->
  <div class="session-form">
    <form action="" method="post">
      {% csrf_token %}
      {{ form.as_p }}
    </form>
  </div>

templates/workouts/session_list.html
<!-- patcurryworks.com/templates/workouts/session_list.html -->
{% extends "base.html" %}

{% block content %}
<div class="sessions">
  <h1>Session List</h1>
  <a href="{% url 'workouts:SessionCreate' %}">Create New Session</a>
  <div class="session-list">
  {% if object_list %}
  {% for session in object_list %}
  <p><a href="{% url 'workouts:SessionDetail' session.pk %}">{{ session.title }} - {{ session.pub_date|date:"Y-m-d" }}</a></p>
  {% endfor %}
  {% else %}
  <p>no sessions yet</p>
  {% endif %}
  </div>
</div>
{% endblock content %}

templates/workouts/set_create.html
<!-- patcurryworks/templates/workouts/set_create.html -->
{% extends "base.html" %}
{% load static %}

{% block content %}
<div class="sets">
  <h1>Set Create</h1>
  {% include "workouts/set_form.html" %}
</div>
{% endblock content %}

templates/workouts/set_form.html
<!-- patcurryworks.com/templates/workouts/set_form.html -->
  <div class="set-form">
    <form action="" method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <input type="submit" value="Submit">
    </form>
  </div>

templates/workouts/set_list.html
<!-- patcurryworks.com/templates/workouts/set_list.html -->
{% extends "base.html" %}

{% block content %}
<div class="set">
  <h1>Set List</h1>
  <div class="set-list">
  {% if object_list %}
  {% for set in object_list %}
  <h4>{{ set.session }}</h4>
  <h4>{{ set.exercise }}</h4>
  <h4>{{ set.amount }}</h4>
  <h4>{{ set.units }}</h4>
  {% endfor %}
  {% else %}
  <p>no sets yet</p>
  {% endif %}
  </div>
</div>
{% endblock content %}

templates/workouts/workout_index.html
<!-- patcurryworks.com/templates/workouts/workout_index.html -->
{% extends "base.html" %}

{% block content %}
<div class="workout-index">
  <h1>Workout!</h1>
  <hr />
  <h4><a href="{% url 'workouts:SessionList' %}">Sessions</a></h4>
  <p><a href="{% url 'workouts:SessionCreate' %}">New Session</a></p>
  <hr />
  <h4><a href="{% url 'workouts:ExerciseList' %}">Exercises</a></h4>
  <p><a href="{% url 'workouts:ExerciseCreate' %}">New Exercise</a></p>
</div>
{% endblock content %}