bio/urls.py
# patcurryworks.com/bio/urls.py
from django.urls import path
from bio import views

app_name = 'bio'


urlpatterns = [
    path('', views.index, name='index'),
    path('resume', views.resume, name='resume'),
]

blog/urls.py
# patcurryworks.com/blog/urls.py
from django.urls import path, re_path
from blog import views

app_name='blog'

urlpatterns = [
    path('', views.post_list, name='post_list'),
    re_path('^(?P<post_slug>[-\w]*)/$', views.post_detail, name='post_detail'),
    #path('', views.Index.as_view(), name='index'),
]

blog/models.py
# patcurryworks.com/blog/models.py
from django.db import models
from django.utils.text import slugify


class Post(models.Model):
    date_created = models.DateTimeField(auto_now_add=True)
    title = models.CharField(max_length=100, blank=True, null=True)
    text = models.TextField(blank=True, null=True)
    post_slug = models.SlugField(max_length=100, blank=True, null=True)

    def save(self, *args, **kwargs):
        self.post_slug = slugify(self.title)
        super(Post, self).save(*args, **kwargs)

blog/views.py
# patcurryworks.com/blog/views.py
from django.core import serializers
from django.views import View
from django.shortcuts import render, get_object_or_404

from blog.models import Post

def post_list(request):
    post_list = Post.objects.all()
    context = {'post_list': post_list}
    response = render(request, 'blog/post_list.html', context)
    return response

def post_detail(request, post_slug):
    post = get_object_or_404(Post, post_slug=post_slug)
    context = {'post': post}
    response = render(request, 'blog/post_detail.html', context)
    return response

templates/blog/post_detail.html
<!-- patcurryworks.com/blog/templates/blog/post_detail.html -->

<p><a class="link blog" href="{% url 'blog:post_list' %}">Post List</a></p>

<p>Title: {{ post.title }}</p>
<p>Text: {{ post.text }}</p>
<p>Slug: {{ post.post_slug }}</p>
<p>Date: {{ post.date_created }}</p>

templates/blog/post_list.html
<!-- patcurryworks.com/templates/blog/post_list.html -->
{% extends "base.html" %}
{% load static %}

{% block content %}
<div class="blog">
  <h1>Blog</h1>
{% if post_list %}
  {% for post in post_list %}
    <p><a href="{% url 'blog:post_detail' post.post_slug %}">{{ post.title }}</a></p>

  {% endfor %}
{% else %}
  <p>No posts yet</p>
{% endif %}

</div>
{% endblock content %}