bio/urls.py
# patcurryworks.com/bio/urls.py
from django.urls import path
from bio import views

app_name = 'bio'


urlpatterns = [
    path('', views.index, name='index'),
    path('resume', views.resume, name='resume'),
]

blog/urls.py
# patcurryworks.com/blog/urls.py
from django.urls import path, re_path
from blog import views

app_name='blog'

urlpatterns = [
    path('', views.post_list, name='post_list'),
    re_path('^(?P<post_slug>[-\w]*)/$', views.post_detail, name='post_detail'),
    #path('', views.Index.as_view(), name='index'),
]

workouts/urls.py
from django.urls import path, re_path
from django.views.generic import TemplateView
from workouts import views
from workouts import api_views

app_name='workouts'

urlpatterns = [

    ############################
    # normal django view urls
    ############################
    # workouts index view
    path('', TemplateView.as_view(template_name='workouts/workout_index.html'), name='WorkoutIndex'),

    # sessions
    path('sessions/', views.SessionList.as_view(), name='SessionList'),
    path('sessions/new/', views.SessionCreate.as_view(), name='SessionCreate'),
    re_path(r'^sessions/(?P<pk>[0-9]+)/$', views.SessionDetail.as_view(), name='SessionDetail'),
    re_path(r'^sessions/(?P<pk>[0-9]+)/update/$', views.SessionUpdate.as_view(), name='SessionUpdate'),
    re_path(r'^sessions/(?P<pk>[0-9]+)/delete/$', views.SessionDelete.as_view(), name='SessionDelete'),

    # sessions - sets
    re_path(r'^sessions/(?P<pk>[0-9]+)/sets/$', views.SetListBySession.as_view(), name='SetListBySession'),
    re_path(r'^sessions/(?P<pk>[0-9]+)/sets/new$', views.SetCreate.as_view(), name='SetCreate'),


    # exercises
    path('exercises/', views.ExerciseList.as_view(), name='ExerciseList'),
    path('exercises/new/', views.ExerciseCreate.as_view(), name='ExerciseCreate'),
    re_path(r'^exercises/(?P<slug>[-\w]*)/$', views.ExerciseDetail.as_view(), name='ExerciseDetail'),
    re_path(r'^exercises/(?P<slug>[-\w]*)/update/$', views.ExerciseUpdate.as_view(), name='ExerciseUpdate'),
    re_path(r'^exercises/(?P<slug>[-\w]*)/delete/$', views.ExerciseDelete.as_view(), name='ExerciseDelete'),

    # exercises - sets
    re_path(r'^exercises/(?P<slug>[-\w]*)/sets/$', views.SetListByExercise.as_view(), name='SetListByExercise'),



    ############################
    # django rest framework urls
    ############################

    # sessions
    path('api/sessions/', api_views.SessionList.as_view(), name='SessionListAPI'),
    re_path(r'^api/sessions/(?P<pk>[0-9]+)/$', api_views.SessionDetail.as_view(), name='SessionDetailAPI'),

    #sets
    path('api/sets/', api_views.SetList.as_view(), name='SetListAPI'),
    re_path(r'^api/sets/(?P<pk>[0-9]+)/$', api_views.SetDetail.as_view(), name='SetDetailAPI'),

    # exercises
    path('api/exercises/', api_views.ExerciseList.as_view(), name='ExerciseListAPI'),
    re_path(r'^api/exercises/(?P<pk>[0-9]+)/$', api_views.ExerciseDetail.as_view(), name='ExerciseDetailAPI'),

    ############################
    # graphql urls ?
    ############################

]

templates/base.html
<!-- patcurryworks.com/templates/base.html -->
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="author" content="Patrick Curry">
    <meta name="description" content="Pat Curry Works is Patrick Curry's personal website.">
    <meta name="keywords" content="HTML, CSS, JavaScript, Python, Django, React, Resume, Portfolio, Blog">

    <title>Pat Curry Works</title>

    <link rel="stylesheet" href="{% static 'css/base-style.css' %}">

    {% block head %}
    {% endblock head %}

  </head>
  <body>
    <div class="page">


      <div class="header">
        <a class="link home" href="{% url 'home' %}">Home</a>
        <a class="link blog" href="{% url 'blog:post_list' %}">Blog</a>
<!-- 
        <a class="link workouts" href="{% url 'workouts:WorkoutIndex' %}">Workout App</a>
        <a class="link react" href="#">React Stuff</a>
-->
        <a class="link bio" href="{% url 'bio:index' %}">Bio</a>
        <a class="link resume" href="{% url 'bio:resume' %}">Resume</a>
      </div>

      {% block content %}

      {% endblock content %}

      <div class="footer">
        <a class="link" href="https://github.com/patcurry/patcurryworks.com" target="_blank">GitHub</a>
      </div>
      
    </div>
    <script src="{% static 'js/sanity.js' %}"></script>
  </body>
</html>